import os
import glob


def cleanupAbaqusJunk():

    # .exception files are made when Abaqus exits with an error. Files generated by Abaqus can be used for debugging
    exception_file = glob.glob("*.exception")  # returns list
    if not exception_file:  # if list is empty
        pass
    else:  # If there is an exception file
        return

    extension_list = [
        "*.abq",
        "*.cid",
        "*.com",
        "*.inp",
        "*.ipm",
        "*.log",
        "*.mdl",
        "*.msg",
        "*.pac",
        "*.prt",
        "*.res",
        "*.sel",
        "*.simlog",
        "*.stt",
        "*.rpy*",
        "*.dat",
        # "*.odb",
        # "*.sta",
    ]
    for ext in extension_list:
        for file in glob.glob(ext):
            os.remove(file)

    os.chdir("../..")

    for file in glob.glob("*.rec"):
        os.remove(file)
    for file in glob.glob("*.rpy*"):
        if file == "abaqus.rpy":
            pass
        else:
            os.remove(file)
